version: "3.8" # Version of Docker Compose to be used.

services:
  db: # Definition of the PostgreSQL database service.
    image: postgres:latest # Docker image used to create the container, in this case, the latest version of PostgreSQL.
    restart: always # Configuration to restart the container whenever Docker or the operating system restarts.
    environment:
      - POSTGRES_USER=postgres # Username for the PostgreSQL database.
      - POSTGRES_PASSWORD=postgres # Password for the PostgreSQL database user.
    ports:
      - "5432:5432" # Mapping port 5432 of the container to port 5432 of the host.
    volumes:
      - db:/var/lib/postgresql/data # Mounting a volume to persist database data in the /var/lib/postgresql/data directory inside the container.

  pgadmin: # Definition of the pgAdmin service.
    image: dpage/pgadmin4 # Docker image used to create the container, which is the official pgAdmin 4 image.
    container_name: pgadmin # Container name.
    restart: always # Configuration to restart the container whenever Docker or the operating system restarts.
    ports:
      - "5050:80" # Mapping port 5050 of the container to port 80 of the host.
    environment:
      - PGADMIN_DEFAULT_EMAIL=johanjimenez0210@gmail.com # Default email for the admin account in pgAdmin.
      - PGADMIN_DEFAULT_PASSWORD=123123123 # Default password for the admin account in pgAdmin.

volumes:
  db: # Definition of a volume named "db".
    driver: local # Type of local volume driver.

  cache: # Definition of a volume named "cache".
    driver: local # Type of local volume driver.
